'use client'

/**
 * ExportButton — Export dialogue as PDF or TXT.
 */

import { useState } from 'react'
import { Download } from 'lucide-react'
import toast from 'react-hot-toast'
import type { DialogueLine } from '@/types'

interface Props {
  lines: DialogueLine[]
  title: string
}

export default function ExportButton({ lines, title }: Props) {
  const [open, setOpen] = useState(false)

  function exportTxt() {
    const content = [
      `SolVurai — சொல்வுரை`,
      `${title}`,
      `Generated: ${new Date().toLocaleString('ta-IN')}`,
      '─'.repeat(40),
      '',
      ...lines.map(l => `${l.speaker}:\n${l.text}${l.translation ? `\n(${l.translation})` : ''}`),
      '',
      '─'.repeat(40),
      'Generated by SolVurai AI — solvurai.app',
    ].join('\n')

    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' })
    const url  = URL.createObjectURL(blob)
    const a    = document.createElement('a')
    a.href     = url
    a.download = `${title.replace(/\s+/g, '_')}.txt`
    a.click()
    URL.revokeObjectURL(url)
    toast.success('TXT exported!')
    setOpen(false)
  }

  async function exportPdf() {
    try {
      const { jsPDF } = await import('jspdf')
      const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })

      // Header
      doc.setFillColor(10, 10, 20)
      doc.rect(0, 0, 210, 297, 'F')

      doc.setFontSize(20)
      doc.setTextColor(255, 107, 26)
      doc.text('SolVurai', 20, 25)

      doc.setFontSize(10)
      doc.setTextColor(150, 150, 180)
      doc.text('AI Tamil Dialogue Platform', 20, 32)

      doc.setFontSize(14)
      doc.setTextColor(255, 255, 255)
      doc.text(title, 20, 45)

      doc.setFontSize(8)
      doc.setTextColor(100, 100, 130)
      doc.text(`Generated: ${new Date().toLocaleString()}`, 20, 52)

      // Divider
      doc.setDrawColor(255, 107, 26)
      doc.line(20, 56, 190, 56)

      // Dialogue
      let y = 66
      lines.forEach((line, i) => {
        if (y > 270) { doc.addPage(); y = 20 }

        doc.setFontSize(9)
        doc.setTextColor(i % 2 === 0 ? 255 : 168, i % 2 === 0 ? 107 : 85, i % 2 === 0 ? 26 : 247)
        doc.text(line.speaker + ':', 20, y)
        y += 6

        doc.setFontSize(10)
        doc.setTextColor(220, 220, 240)
        const textLines = doc.splitTextToSize(line.text, 160)
        doc.text(textLines, 25, y)
        y += textLines.length * 6

        if (line.translation) {
          doc.setFontSize(8)
          doc.setTextColor(120, 120, 150)
          doc.text(`(${line.translation})`, 25, y)
          y += 5
        }
        y += 4
      })

      // Footer
      doc.setFontSize(7)
      doc.setTextColor(80, 80, 100)
      doc.text('Generated by SolVurai AI — DTEC 2026', 20, 290)

      doc.save(`${title.replace(/\s+/g, '_')}.pdf`)
      toast.success('PDF exported!')
    } catch (e) {
      toast.error('PDF export failed')
    }
    setOpen(false)
  }

  return (
    <div className="relative">
      <button
        onClick={() => setOpen(!open)}
        title="Export"
        className="w-8 h-8 rounded-lg flex items-center justify-center text-white/40 hover:text-white hover:bg-white/10 transition-all duration-150"
      >
        <Download size={14} />
      </button>
      {open && (
        <div
          className="absolute right-0 top-10 glass rounded-xl py-1 z-50 min-w-[120px] shadow-xl"
          style={{ border: '1px solid rgba(255,255,255,0.1)' }}
        >
          <button onClick={exportTxt}
            className="w-full px-4 py-2 text-sm text-white/60 hover:text-white hover:bg-white/5 text-left transition-colors">
            Export TXT
          </button>
          <button onClick={exportPdf}
            className="w-full px-4 py-2 text-sm text-white/60 hover:text-white hover:bg-white/5 text-left transition-colors">
            Export PDF
          </button>
        </div>
      )}
    </div>
  )
}
